name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - elixir: "1.17.3"
            otp: "26.2"
          - elixir: "1.18.4"
            otp: "27.3.4"
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4

      - name: Install Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - uses: actions/cache@v4
        with:
          path: deps
          key: mix-deps-${{ hashFiles('**/mix.lock') }}

      - name: Install mix dependencies
        run: mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

      - name: Check unused deps
        run: mix deps.unlock --check-unused

      - name: Run tests
        run: mix test

      - uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--remove-orphans"
          up-flags: "--no-start"

      - name: Run integration tests
        run: |
          docker compose up -d
          sleep 60
          mix test --only integration
          docker compose down --remove-orphans
